name: Mise à jour du badge

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Toutes les heures

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Compter le nombre de commits
        id: commit_count
        run: echo "count=$(git rev-list --count HEAD)" >> "$GITHUB_OUTPUT"

      - name: Créer le dossier badges
        run: mkdir -p badges

      - name: Mettre à jour le badge
        run: |
          echo "{\"schemaVersion\":1,\"label\":\"Commits\",\"message\":\"${{ steps.commit_count.outputs.count }}\",\"color\":\"blue\"}" > badges/badge.json

      - name: Commit et push des modifications
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add badges/badge.json
          git diff --cached --quiet || git commit -m "Mise à jour automatique du badge"
          git push